name: Cloudformation nag
on: [push]
# on:
#     pull_request_target:
#         branches:
#             -main
jobs: 
    cloudformation-nag: 
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v3
            - run: eval "$(/home/linuxbrew/.limuxbrew/bin/brew shellenv)"
            - run : brew install ruby brew-gem
            - run : derw gem install cfn-nag 
            