
name: Integration tests

on: [push]

jobs:
  taskcat:
    name: Run taskcat tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: es-east-1

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Install Ruby-full
      run: |
        sudo apt-get update
        sudo apt-get install -y ruby-full

    - name: Install cfn-nag gem
      run: |
        gem install cfn-nag --user-install
        export PATH=$PATH:$HOME/.gem/ruby/3.0.0/bin

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.11

    - name: Install dependencies and run taskcat tests
      run: |
        pip install -r requirements.txt
        taskcat test run

    - name: Run taskcat test run
      uses: ShahradR/action-taskcat@v1
      with:
        commands: test run
        update_taskcat: true
        update_cfn_lint: true
