name: Cloudformation nag
on: [push]
# on:
#     pull_request_target:
#         branches:
#             -main
jobs: 
    cloudformation-nag: 
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v3
            - run: echo "probando job"