name: Cloudformation nag
on: [push]
# on:
#     pull_request_target:
#         branches:
#             -main
jobs: 
    cloudformation-nag: 
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v3    
            - run: |
                eval "$(/home/linuxbrew/.limuxbrew/bin/brew shellenv)"
                brew install ruby brew-gem
                berw gem install cfn-nag 
            