name: Cloudformation nag
on: [push]
#   push:
#     branches:
#       - main

jobs:
  cloudformation-nag:
    runs-on: ubuntu-latest
    steps:
      - name: Install Homebrew
        run: |
          sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
          test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)

      - name: Install Ruby and cfn-nag
        run: |
          brew install ruby brew-gem
          brew gem install cfn-nag

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Ruby and cfn-nag (again?)
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install ruby brew-gem
          brew gem install cfn-nag
